[workspace]
members = [
    "crates/evm-db",
    "crates/evm-core",
    "crates/evm-canister"
]
exclude = [
    "vendor/stable-structures"
    ,"vendor/revm"
]
resolver = "2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = "symbols"
debug = false
